export const QUOTES = [
  "The expert in anything was once a beginner. Keep going.",
  "You're not just studying. You're building a better memory.",
  "Every card you review is compound interest on your understanding.",
  "Recall beats re-reading. You already chose the smarter path.",
  "The forgetting curve is real. You just beat it.",
  "Small sessions, consistently. That's the whole secret.",
  "Anki users score higher. You now have an unfair advantage.",
  "Sleep after studying. Your brain consolidates while you rest.",
  "You uploaded the notes. Now let the algorithm do the work.",
  "We believe in you. All the best.",
  "If you want to master something, teach it to yourself.",
  "Don't practice until you get it right. Practice until you can't get it wrong.",
  "Consistency is the ultimate competitive advantage.",
  "Your brain is a muscle. Spaced repetition is the workout.",
  "Don't trust your future self to remember. Trust the algorithm.",
  "A year from now, you'll wish you had started today.",
  "Slow progress is still progress.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Focus on the step in front of you, not the whole staircase.",
  "Hard work beats talent when talent doesn't work hard.",
  "Learning is not a spectator sport.",
  "Active recall is hard because it works.",
  "Embrace the struggle. That's where the learning happens.",
  "Knowledge is power. Retention is superpower.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Study smarter, not longer.",
  "Rest is a part of the program.",
  "What gets measured gets managed. Keep doing your reviews.",
  "A moment of pain, a lifetime of retention.",
  "You are one flashcard closer to your goal.",
  "Don't cram. Space it out.",
  "The best way to predict your future is to create it.",
  "Trust the process. Trust the algorithm.",
  "Forget the mistake, remember the lesson.",
  "Every review strengthens the neural pathway.",
  "Make it stick.",
  "Great things are not done by impulse, but by a series of small things brought together.",
  "Do something today that your future self will thank you for.",
  "Doubt kills more dreams than failure ever will.",
  "Discipline is choosing between what you want now and what you want most.",
  "There are no shortcuts to any place worth going.",
  "Believe you can and you're halfway there.",
  "Strive for progress, not perfection.",
  "Education is the passport to the future.",
  "The beautiful thing about learning is that no one can take it away from you.",
  "It always seems impossible until it's done.",
  "Don't let what you cannot do interfere with what you can do.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "I find that the harder I work, the more luck I seem to have.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "You don't have to be great to start, but you have to start to be great.",
  "The only place where success comes before work is in the dictionary.",
  "Don't watch the clock; do what it does. Keep going.",
  "The secret of getting ahead is getting started.",
  "Quality is not an act, it is a habit.",
  "Action is the foundational key to all success.",
  "What you do today can improve all your tomorrows.",
  "Setting goals is the first step in turning the invisible into the visible.",
  "It's not about perfect. It's about effort.",
  "You miss 100% of the shots you don't take."
]
