import React from 'react';
import Link from 'next/link';
import type { Metadata } from 'next';

const SITE_URL = 'https://notes2cards.study';

export const metadata: Metadata = {
  title: 'Privacy Policy — notes2cards',
  description: 'Read the Privacy Policy for notes2cards — how we collect, use, and protect your data.',
  alternates: {
    canonical: `${SITE_URL}/privacy`,
  },
  openGraph: {
    type: 'website',
    url: `${SITE_URL}/privacy`,
    siteName: 'notes2cards',
    title: 'Privacy Policy — notes2cards',
    description: 'Read the Privacy Policy for notes2cards — how we collect, use, and protect your data.',
    images: [
      {
        url: '/og-image-1200x630.png',
        width: 1200,
        height: 630,
        alt: 'notes2cards — AI-powered Anki flashcard generator',
      },
    ],
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    site: '@notes2cards',
    title: 'Privacy Policy — notes2cards',
    description: 'Read the Privacy Policy for notes2cards — how we collect, use, and protect your data.',
    images: ['/og-image-1200x630.png'],
  },
};


export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-[#0A0A0A] text-white/80 py-20 px-6"
      style={{ fontFamily: 'Outfit, sans-serif' }}>
      <div className="max-w-3xl mx-auto">

        <Link href="/" className="text-[#6DB5FF] hover:underline mb-8 inline-block text-sm">
          ← Back to Home
        </Link>

        <h1 className="text-4xl font-bold text-white mb-2">Privacy Policy</h1>
        <p className="text-white/40 text-sm mb-12">Last updated: June 2026</p>

        <p className="mb-8 leading-relaxed">
          This Privacy Policy explains how notes2cards (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;) collects,
          uses, and protects your personal information when you use our Service. By using
          notes2cards, you agree to the practices described here.
        </p>

        {/* ── 1 ── */}
        <Section title="1. Information We Collect">
          <p><strong className="text-white">Information you provide directly:</strong></p>
          <ul className="mt-3 mb-4 space-y-2 list-disc list-inside text-white/65">
            <li>Email address (required for account creation)</li>
            <li>Full name (optional, for personalisation)</li>
            <li>Password (stored as a one-way hash — we never see your plaintext password)</li>
            <li>Marketing preference (whether you opted in to product updates at signup)</li>
          </ul>
          <p><strong className="text-white">Information generated by the Service:</strong></p>
          <ul className="mt-3 mb-4 space-y-2 list-disc list-inside text-white/65">
            <li>Usage data: pages processed per month, plan type, cycle reset date</li>
            <li>Generation logs: file name, file type, page count, AI token counts (used to calibrate pricing — no file content is stored)</li>
            <li>Session tokens (for authentication, stored in secure cookies)</li>
          </ul>
          <p><strong className="text-white">Payment information:</strong></p>
          <p className="mt-3 text-white/65">
            All payment processing is handled entirely by Lemon Squeezy. We never receive,
            store, or have access to your credit card or payment details. We only receive a
            customer ID and subscription status confirmation.
          </p>
        </Section>

        {/* ── 2 ── */}
        <Section title="2. What We Do NOT Collect">
          <ul className="space-y-2 list-disc list-inside text-white/65">
            <li>The <strong className="text-white">content</strong> of files you upload — they are processed transiently and deleted immediately after flashcard generation</li>
            <li>The <strong className="text-white">content</strong> of generated flashcards — these exist only in your browser/Anki</li>
            <li>Precise location data (we use country-level only, if applicable)</li>
            <li>Tracking pixels, ad network cookies, or cross-site behavioural data</li>
            <li>Your uploaded files for AI model training — ever</li>
          </ul>
        </Section>

        {/* ── 3 ── */}
        <Section title="3. How We Use Your Information">
          <ul className="space-y-2 list-disc list-inside text-white/65">
            <li>To authenticate you and maintain your account session</li>
            <li>To enforce your plan&apos;s monthly page quota and reset it correctly</li>
            <li>To send transactional emails (e.g., receipts, password resets) — these are always sent regardless of marketing preference</li>
            <li>To send product updates, tips, and offers — <strong className="text-white">only if you explicitly opted in at signup</strong></li>
            <li>To monitor aggregate token usage (anonymised) to ensure the service remains financially sustainable</li>
            <li>To investigate abuse, fraud, or violations of our Terms of Service</li>
          </ul>
        </Section>

        {/* ── 4 ── */}
        <Section title="4. How We Share Your Information">
          <p>
            We do <strong className="text-white">not</strong> sell your personal data. We share data
            only with the following third-party service providers, solely to operate the Service:
          </p>
          <ul className="mt-4 space-y-3 list-disc list-inside text-white/65">
            <li>
              <strong className="text-white">Supabase</strong> (database &amp; authentication) — stores your account data,
              usage counts, and generation logs. Data is hosted on servers in the region you signed up from.
            </li>
            <li>
              <strong className="text-white">Google Gemini API</strong> — receives your uploaded files temporarily
              for flashcard generation. Files are deleted from Google&apos;s servers within seconds
              of processing via the Gemini File API delete endpoint. Google&apos;s data use is governed
              by their API terms.
            </li>
            <li>
              <strong className="text-white">Lemon Squeezy</strong> (payments) — handles all payment processing.
              We receive only your subscription status; no card data ever reaches our servers.
            </li>
            <li>
              <strong className="text-white">Vercel</strong> (hosting &amp; CDN) — hosts the web application.
              Request logs (IP address, URL, timestamp) may be stored for up to 30 days for security purposes.
            </li>
          </ul>
        </Section>

        {/* ── 5 ── */}
        <Section title="5. Data Retention">
          <ul className="space-y-2 list-disc list-inside text-white/65">
            <li><strong className="text-white">Uploaded files:</strong> deleted from Gemini servers immediately after processing (within seconds)</li>
            <li><strong className="text-white">Generation logs:</strong> retained indefinitely for quota calibration; contain no file content — only token counts and metadata</li>
            <li><strong className="text-white">Account data:</strong> retained until you delete your account</li>
            <li><strong className="text-white">Marketing subscriber list:</strong> retained until you unsubscribe; you can opt out at any time by emailing us</li>
            <li><strong className="text-white">Payment records:</strong> retained as required by applicable financial regulations (typically 7 years)</li>
          </ul>
        </Section>

        {/* ── 6 ── */}
        <Section title="6. Cookies & Tracking">
          <p>
            We use only the following types of cookies:
          </p>
          <ul className="mt-4 space-y-2 list-disc list-inside text-white/65">
            <li><strong className="text-white">Authentication cookies:</strong> Supabase session tokens required to keep you logged in. These are strictly necessary and cannot be disabled.</li>
            <li><strong className="text-white">Preference cookies:</strong> We store your UI preferences (dark/light theme, font size, default settings) in browser localStorage. This data never leaves your device.</li>
          </ul>
          <p className="mt-4">
            We do <strong className="text-white">not</strong> use advertising cookies, analytics pixels, or any
            third-party tracking scripts.
          </p>
        </Section>

        {/* ── 7 ── */}
        <Section title="7. Your Rights">
          <p>Depending on your location, you may have the following rights:</p>
          <ul className="mt-4 space-y-2 list-disc list-inside text-white/65">
            <li><strong className="text-white">Access:</strong> Request a copy of the personal data we hold about you</li>
            <li><strong className="text-white">Correction:</strong> Request correction of inaccurate personal data</li>
            <li><strong className="text-white">Deletion:</strong> Delete your account and all associated data via Account Settings → Danger Zone, or by emailing us</li>
            <li><strong className="text-white">Opt-out of marketing:</strong> Unsubscribe from marketing emails at any time using the unsubscribe link in any email, or by emailing us</li>
            <li><strong className="text-white">Data portability:</strong> Request an export of your data in a machine-readable format</li>
          </ul>
          <p className="mt-4">
            To exercise any of these rights,{' '}
            <a href="/contact" className="text-[#6DB5FF] hover:underline">
              contact us here
            </a>
            . We respond to all requests within 30 days.
          </p>
        </Section>

        {/* ── 8 ── */}
        <Section title="8. Data Security">
          <p>
            We implement the following security measures:
          </p>
          <ul className="mt-4 space-y-2 list-disc list-inside text-white/65">
            <li>All data in transit is encrypted via TLS 1.2+</li>
            <li>Passwords are hashed using bcrypt (managed by Supabase Auth)</li>
            <li>Database access requires authenticated API calls; the database is not publicly exposed</li>
            <li>Row Level Security (RLS) is enabled on all Supabase tables — users can only access their own data</li>
            <li>API routes enforce authentication before any data operation</li>
          </ul>
          <p className="mt-4">
            Despite these measures, no method of internet transmission is 100% secure. In the
            event of a data breach affecting your personal information, we will notify you within
            72 hours of becoming aware of it.
          </p>
        </Section>

        {/* ── 9 ── */}
        <Section title="9. Children's Privacy">
          <p>
            The Service is not directed to children under 13. We do not knowingly collect
            personal information from children under 13. If we become aware that a child under
            13 has provided us with personal information, we will delete it promptly.
            If you believe a child under 13 has created an account, please{' '}
            <a href="/contact" className="text-[#6DB5FF] hover:underline">
              contact us
            </a>.
          </p>
        </Section>

        {/* ── 10 ── */}
        <Section title="10. Changes to This Policy">
          <p>
            We may update this Privacy Policy from time to time. We will notify you of
            material changes via email or a prominent notice on the Service. The &quot;Last
            updated&quot; date at the top of this page reflects the most recent revision.
            Continued use after changes take effect constitutes acceptance of the updated Policy.
          </p>
        </Section>

        {/* ── 11 ── */}
        <Section title="11. Contact Us">
          <p>
            For privacy-related questions, data requests, or to report a concern,{' '}
            <a href="/contact" className="text-[#6DB5FF] hover:underline">
              use our contact form
            </a>
            . We respond to all requests within 30 days.
          </p>
        </Section>

        <div className="mt-16 pt-8 border-t border-white/[0.06]">
          <Link href="/" className="text-[#6DB5FF] hover:underline text-sm">← Back to Home</Link>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-10">
      <h2 className="text-xl font-semibold text-white mb-4">{title}</h2>
      <div className="text-white/65 leading-relaxed text-[15px]">{children}</div>
    </div>
  );
}
